CREATE TABLE todo_items (
  id VARCHAR2(36) PRIMARY KEY,
  title VARCHAR2(500) NOT NULL,
  completed NUMBER(1) DEFAULT 0 NOT NULL CHECK (completed IN (0, 1)),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
