apiVersion: v1
kind: Secret
metadata:
  name: oci-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "auth": "OKEWorkloadIdentity",
      "region": "eu-frankfurt-1"
    }
