apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  type: oci
  # Flux appends HelmRelease.spec.chart.spec.chart to this OCI registry path.
  url: oci://docker.io/envoyproxy
