apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: gateway-helm
      version: v1.9.0
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    deployment:
      pod:
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
            effect: NoSchedule
