apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: karpenter-provider-oci
  namespace: karpenter
spec:
  interval: 1h0m0s
  url: https://oracle.github.io/karpenter-provider-oci/charts
