apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-oci-runtime
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./platform/crossplane/oci-runtime
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-oci-family
  namespace: flux-system
spec:
  dependsOn:
    - name: crossplane-oci-runtime
  interval: 1m0s
  path: ./platform/crossplane/oci-family
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
  healthChecks:
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      name: oracle-provider-family-oci
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-oci-database
  namespace: flux-system
spec:
  dependsOn:
    - name: crossplane-oci-family
  interval: 1m0s
  path: ./platform/crossplane/oci-database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
  healthChecks:
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      name: provider-oci-database
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-oci-objectstorage
  namespace: flux-system
spec:
  dependsOn:
    - name: crossplane-oci-family
  interval: 1m0s
  path: ./platform/crossplane/oci-objectstorage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
  healthChecks:
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      name: provider-oci-objectstorage
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-oci-networking
  namespace: flux-system
spec:
  dependsOn:
    - name: crossplane-oci-family
  interval: 1m0s
  path: ./platform/crossplane/oci-networking
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
  healthChecks:
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      name: provider-oci-networking
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-oci-kms
  namespace: flux-system
spec:
  dependsOn:
    - name: crossplane-oci-family
  interval: 1m0s
  path: ./platform/crossplane/oci-kms
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
  healthChecks:
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      name: provider-oci-kms
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-oci-config
  namespace: flux-system
spec:
  dependsOn:
    - name: crossplane-oci-objectstorage
    - name: crossplane-oci-database
    - name: crossplane-oci-networking
    - name: crossplane-oci-kms
  interval: 1m0s
  path: ./platform/crossplane/oci-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
