apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-oci-networking
spec:
  package: ghcr.io/oracle/provider-oci-networking:v1.1.0
  runtimeConfigRef:
    name: oci-workload-identity
