apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ocir-pull-secret.yaml
  - todo-api.yaml
  - todo-api-hpa.yaml
  - todo-ui-bridge.yaml
  - todo-routes.yaml
