apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-vault-reader
  namespace: crossplane-system
  labels:
    app.kubernetes.io/part-of: todo-db-app
    app.kubernetes.io/component: secrets
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: todo-vault
  namespace: crossplane-system
  labels:
    app.kubernetes.io/part-of: todo-db-app
    app.kubernetes.io/component: secrets
spec:
  provider:
    oracle:
      compartment: ocid1.compartment.oc1..aaaaaaaawccfklp2wj4c5ymigrkjfdhcbcm3u5ripl2whnznhmvgiqdatqgq
      encryptionKey: ocid1.key.oc1.eu-frankfurt-1.cbrcv4plaahh4.abtheljrkwzqpqwltve34cn33yz7226wrcsbh2v65tzojmygi7uej6wqnmbq
      principalType: Workload
      region: eu-frankfurt-1
      serviceAccountRef:
        name: todo-vault-reader
      vault: ocid1.vault.oc1.eu-frankfurt-1.cbrcv4plaahh4.abtheljrz3llvhibeprbk3pp5si7vznjxvmplux3xly5rgipubkvhgvav34a
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: todo-adb-admin-password
  namespace: crossplane-system
  labels:
    app.kubernetes.io/part-of: todo-db-app
    app.kubernetes.io/component: secrets
spec:
  allowRepeat: true
  digits: 4
  length: 24
  noUpper: false
  symbols: 0
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: todo-adb-admin
  namespace: crossplane-system
  labels:
    app.kubernetes.io/part-of: todo-db-app
    app.kubernetes.io/component: secrets
spec:
  deletionPolicy: Delete
  refreshInterval: 1h0m0s
  secretStoreRefs:
    - kind: SecretStore
      name: todo-vault
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: todo-adb-admin-password
  updatePolicy: IfNotExists
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: oke-openspec-codex-todo-adb-admin-eso
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: todo-adb-admin
  namespace: crossplane-system
  labels:
    app.kubernetes.io/part-of: todo-db-app
    app.kubernetes.io/component: secrets
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: SecretStore
    name: todo-vault
  target:
    creationPolicy: Owner
    immutable: true
    name: todo-adb-admin
  data:
    - secretKey: password
      remoteRef:
        key: oke-openspec-codex-todo-adb-admin-eso
